### ISSUE TITLE
Should CX curvature atom values be averaged to get residue curvature?

### ISSUE THREAD

**Issue by edraizen** [bouralab/Prop3D#25]
https://github.com/edraizen/molmimic/blob/a9fbbfa97657fdae68c130f43e71f740ce2cb79b/molmimic/common/featurizer.py#L397

Or look at surfv from honig lab?

Or look a the Shape Index from MaSIF?

**Comment by cmura** [comment]
https://onlinelibrary.wiley.com/doi/epdf/10.1002/prot.22301
